In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import os

data = pd.read_csv('games.csv')
data.head()

AppID                   Name  Release date Estimated owners  Peak CCU  \
0    20200       Galactic Bowling  Oct 21, 2008        0 - 20000         0   
1   655370           Train Bandit  Oct 12, 2017        0 - 20000         0   
2  1732930           Jolt Project  Nov 17, 2021        0 - 20000         0   
3  1355720               Henosis™  Jul 23, 2020        0 - 20000         0   
4  1139950  Two Weeks in Painland   Feb 3, 2020        0 - 20000         0   

   Required age  Price  DLC count  \
0             0  19.99          0   
1             0   0.99          0   
2             0   4.99          0   
3             0   5.99          0   
4             0   0.00          0   

                                      About the game  \
0  Galactic Bowling is an exaggerated and stylize...   
1  THE LAW!! Looks to be a showdown atop a train....   
2  Jolt Project: The army now has a new robotics ...   
3  HENOSIS™ is a mysterious 2D Platform Puzzler w...   
4  ABOUT THE GAME Play as a hacker who has arrang...   

                                 Supported languages  ...  \
0                                        ['English']  ...   
1  ['English', 'French', 'Italian', 'German', 'Sp...  ...   
2                 ['English', 'Portuguese - Brazil']  ...   
3  ['English', 'French', 'Italian', 'German', 'Sp...  ...   
4                     ['English', 'Spanish - Spain']  ...   

  Average playtime two weeks Median playtime forever  \
0                          0                       0   
1                          0                       0   
2                          0                       0   
3                          0                       0   
4                          0                       0   

  Median playtime two weeks             Developers             Publishers  \
0                         0  Perpetual FX Creative  Perpetual FX Creative   
1                         0           Rusty Moyher           Wild Rooster   
2                         0          Campião Games          Campião Games   
3                         0      Odd Critter Games      Odd Critter Games   
4                         0          Unusual Games          Unusual Games   

                                          Categories  \
0  Single-player,Multi-player,Steam Achievements,...   
1  Single-player,Steam Achievements,Full controll...   
2                                      Single-player   
3              Single-player,Full controller support   
4                   Single-player,Steam Achievements   

                            Genres  \
0              Casual,Indie,Sports   
1                     Action,Indie   
2  Action,Adventure,Indie,Strategy   
3           Adventure,Casual,Indie   
4                  Adventure,Indie   

                                                Tags  \
0                        Indie,Casual,Sports,Bowling   
1  Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...   
2                                                NaN   
3  2D Platformer,Atmospheric,Surreal,Mystery,Puzz...   
4  Indie,Adventure,Nudity,Violent,Sexual Content,...   

                                         Screenshots  \
0  https://cdn.akamai.steamstatic.com/steam/apps/...   
1  https://cdn.akamai.steamstatic.com/steam/apps/...   
2  https://cdn.akamai.steamstatic.com/steam/apps/...   
3  https://cdn.akamai.steamstatic.com/steam/apps/...   
4  https://cdn.akamai.steamstatic.com/steam/apps/...   

                                              Movies  
0  http://cdn.akamai.steamstatic.com/steam/apps/2...  
1  http://cdn.akamai.steamstatic.com/steam/apps/2...  
2  http://cdn.akamai.steamstatic.com/steam/apps/2...  
3  http://cdn.akamai.steamstatic.com/steam/apps/2...  
4  http://cdn.akamai.steamstatic.com/steam/apps/2...  

[5 rows x 39 columns]

In [3]:
data1 = data.drop(['About the game','Reviews','Header image','Website','Support url','Support email','Metacritic url','Notes','Screenshots'], axis = 'columns')
data1.head()

AppID                   Name  Release date Estimated owners  Peak CCU  \
0    20200       Galactic Bowling  Oct 21, 2008        0 - 20000         0   
1   655370           Train Bandit  Oct 12, 2017        0 - 20000         0   
2  1732930           Jolt Project  Nov 17, 2021        0 - 20000         0   
3  1355720               Henosis™  Jul 23, 2020        0 - 20000         0   
4  1139950  Two Weeks in Painland   Feb 3, 2020        0 - 20000         0   

   Required age  Price  DLC count  \
0             0  19.99          0   
1             0   0.99          0   
2             0   4.99          0   
3             0   5.99          0   
4             0   0.00          0   

                                 Supported languages Full audio languages  \
0                                        ['English']                   []   
1  ['English', 'French', 'Italian', 'German', 'Sp...                   []   
2                 ['English', 'Portuguese - Brazil']                   []   
3  ['English', 'French', 'Italian', 'German', 'Sp...                   []   
4                     ['English', 'Spanish - Spain']                   []   

   ...  Average playtime forever  Average playtime two weeks  \
0  ...                         0                           0   
1  ...                         0                           0   
2  ...                         0                           0   
3  ...                         0                           0   
4  ...                         0                           0   

   Median playtime forever  Median playtime two weeks             Developers  \
0                        0                          0  Perpetual FX Creative   
1                        0                          0           Rusty Moyher   
2                        0                          0          Campião Games   
3                        0                          0      Odd Critter Games   
4                        0                          0          Unusual Games   

              Publishers                                         Categories  \
0  Perpetual FX Creative  Single-player,Multi-player,Steam Achievements,...   
1           Wild Rooster  Single-player,Steam Achievements,Full controll...   
2          Campião Games                                      Single-player   
3      Odd Critter Games              Single-player,Full controller support   
4          Unusual Games                   Single-player,Steam Achievements   

                            Genres  \
0              Casual,Indie,Sports   
1                     Action,Indie   
2  Action,Adventure,Indie,Strategy   
3           Adventure,Casual,Indie   
4                  Adventure,Indie   

                                                Tags  \
0                        Indie,Casual,Sports,Bowling   
1  Indie,Action,Pixel Graphics,2D,Retro,Arcade,Sc...   
2                                                NaN   
3  2D Platformer,Atmospheric,Surreal,Mystery,Puzz...   
4  Indie,Adventure,Nudity,Violent,Sexual Content,...   

                                              Movies  
0  http://cdn.akamai.steamstatic.com/steam/apps/2...  
1  http://cdn.akamai.steamstatic.com/steam/apps/2...  
2  http://cdn.akamai.steamstatic.com/steam/apps/2...  
3  http://cdn.akamai.steamstatic.com/steam/apps/2...  
4  http://cdn.akamai.steamstatic.com/steam/apps/2...  

[5 rows x 30 columns]

In [4]:
#결측치(Missing data)
print('전체 데이터 건수:', len(data))

전체 데이터 건수: 76987


In [51]:
# Name 데이터는 object값을 가지므로 인코딩을 진행해보았다.

from sklearn.preprocessing import LabelEncoder

Name = data1['Name']

df_Name = pd.DataFrame(Name)

label_encoder = LabelEncoder()
df_Name['Category_encoded_Name'] = label_encoder.fit_transform(df_Name['Name'])

print("Original DataFrame:")
print(df_Name[['Name']])
print("\nDataFrame with Label Encoded Column:")
print(df_Name[['Category_encoded_Name']])


Original DataFrame:
                         Name
0            Galactic Bowling
1                Train Bandit
2                Jolt Project
3                    Henosis™
4       Two Weeks in Painland
...                       ...
76982                Diebrary
76983            Flutter Away
76984  Surreal House Playtest
76985         Spot the Object
76986     擱淺地 - Dream Antique

[76987 rows x 1 columns]

DataFrame with Label Encoded Column:
       Category_encoded_Name
0                      24695
1                      66605
2                      32459
3                      28268
4                      67498
...                      ...
76982                  16810
76983                  23132
76984                  59780
76985                  57586
76986                  75205

[76987 rows x 1 columns]


In [7]:
# Required age가 어느정도로 분포되어있는지에 대해 알기 위해 중복된 데이터를 삭제한 후 오름차순으로 정렬하였다.

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
import pandas as pd

Required_age = data1['Required age']

df_Required_age = pd.DataFrame(Required_age)

df_Required_age_no_duplicates = df_Required_age.drop_duplicates()

df_Required_age_sorted = df_Required_age_no_duplicates.sort_values(by='Required age', ascending=True)


print("\nDataFrame with Duplicates Removed:")
print(df_Required_age_no_duplicates)

print("\nDataFrame Sorted by Requiredage in Ascending Order:")
print(df_Required_age_sorted)

# 최대 1세부터 21세까지 나와있고 0은 전체 이용가이다.

# Min-Max Scaling (0과 1 사이의 범위로 스케일링)
min_max_scaler = MinMaxScaler()
min_max_scaled_data = min_max_scaler.fit_transform(df_Required_age)

print("Min-Max Scaled Data:")
print(min_max_scaled_data)

# Standard Scaling (Z-score normalization)
standard_scaler = StandardScaler()
standard_scaled_data = standard_scaler.fit_transform(df_Required_age)

print("\nStandard Scaled Data:")
print(standard_scaled_data)

# Robust Scaling (중앙값과 IQR을 사용한 스케일링)
robust_scaler = RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(df_Required_age)

print("\nRobust Scaled Data:")
print(robust_scaled_data)


DataFrame with Duplicates Removed:
       Required age
0                 0
47               17
91               18
107              10
187              13
1025             16
2387              6
3491             14
5122             12
8340             15
9871              3
15187            21
18203             7
25062             5
36170            20
43528             1
49623            19
73662             9

DataFrame Sorted by Requiredage in Ascending Order:
       Required age
0                 0
43528             1
9871              3
25062             5
2387              6
18203             7
73662             9
107              10
5122             12
187              13
3491             14
8340             15
1025             16
47               17
91               18
49623            19
36170            20
15187            21
Min-Max Scaled Data:
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]

Standard Scaled Data:
[[-0.14233801]
 [-0.14233801]
 [-0.14233801]
 ...
 [-0.14233801]


In [8]:
# DLC count가 어느정도로 분포되어있는지에 대해 알기 위해 중복된 데이터를 삭제한 후 오름차순으로 정렬하였다.

DLC_count = data1['DLC count']

df_DLC_count = pd.DataFrame(DLC_count)

df_DLC_count_no_duplicates = df_DLC_count.drop_duplicates()

df_DLC_count_sorted = df_DLC_count_no_duplicates.sort_values(by='DLC count', ascending=True)


print("\nDataFrame with Duplicates Removed:")
print(df_DLC_count_no_duplicates)

print("\nDataFrame Sorted by Requiredage in Ascending Order:")
print(df_DLC_count_sorted)

# Min-Max Scaling (0과 1 사이의 범위로 스케일링)
min_max_scaler = MinMaxScaler()
min_max_scaled_data = min_max_scaler.fit_transform(df_DLC_count)

print("Min-Max Scaled Data:")
print(min_max_scaled_data)

# Standard Scaling (Z-score normalization)
standard_scaler = StandardScaler()
standard_scaled_data = standard_scaler.fit_transform(df_DLC_count)

print("\nStandard Scaled Data:")
print(standard_scaled_data)

# Robust Scaling (중앙값과 IQR을 사용한 스케일링)
robust_scaler = RobustScaler()
robust_scaled_data = robust_scaler.fit_transform(df_DLC_count)

print("\nRobust Scaled Data:")
print(robust_scaled_data)


DataFrame with Duplicates Removed:
       DLC count
0              0
6              1
18             2
22            23
39             7
...          ...
51280         73
60001        159
60883         98
63317         58
64796         80

[94 rows x 1 columns]

DataFrame Sorted by Requiredage in Ascending Order:
       DLC count
0              0
6              1
18             2
69             3
365            4
...          ...
19312        579
3492         678
7575        1555
23291       1968
32933       2366

[94 rows x 1 columns]
Min-Max Scaled Data:
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]

Standard Scaled Data:
[[-0.04047138]
 [-0.04047138]
 [-0.04047138]
 ...
 [-0.04047138]
 [-0.04047138]
 [-0.04047138]]

Robust Scaled Data:
[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


In [56]:
# Full audio languages  데이터는 object값을 가지므로 인코딩을 진행해보았다.

from sklearn.preprocessing import LabelEncoder

Full_audio_languages  = data1['Full audio languages']

df_Full_audio_languages  = pd.DataFrame(Full_audio_languages)

label_encoder = LabelEncoder()
df_Full_audio_languages ['Category_encoded_Full_audio_languages'] = label_encoder.fit_transform(df_Full_audio_languages['Full audio languages'])

print("Original DataFrame:")
print(df_Full_audio_languages [['Full audio languages']])
print("\nDataFrame with Label Encoded Column:")
print(df_Full_audio_languages [['Category_encoded_Full_audio_languages']])




Original DataFrame:
      Full audio languages
0                       []
1                       []
2                       []
3                       []
4                       []
...                    ...
76982          ['English']
76983                   []
76984                   []
76985          ['English']
76986                   []

[76987 rows x 1 columns]

DataFrame with Label Encoded Column:
       Category_encoded_Full_audio_languages
0                                       2043
1                                       2043
2                                       2043
3                                       2043
4                                       2043
...                                      ...
76982                                   1795
76983                                   2043
76984                                   2043
76985                                   1795
76986                                   2043

[76987 rows x 1 columns]


In [21]:
# MAC 칼럼 데이터는 TRUE or False 값을 갖는 bool값이다. 따라서 Mac사용 유저에게 추천해줄 수 있는 데이터를 추출한다.

Mac = data1['Mac']

df_Mac = pd.DataFrame(Mac)

filtered_Mac = df_Mac[df_Mac['Mac'] == True]

print("\nFiltered DataFrame:")
print(filtered_Mac)

# 76983개의 게임 데이터 중 15156 개의 게임 데이터만 Mac 유저에게 추천이 가능하다.


Filtered DataFrame:
        Mac
1      True
3      True
4      True
9      True
11     True
...     ...
76960  True
76961  True
76964  True
76968  True
76983  True

[15156 rows x 1 columns]


In [39]:
# Metacritic score 칼럼 데이터는 비평가들에게 받은 점수로 대부분의 데이터가 0으로 나와있기 떄문에 먼저 0값을 갖는 데이터를 삭제해준다.
#칼럼 데이터는 TRUE or False 값을 갖는 bool값이다. 따라서 Mac사용 유저에게 추천해줄 수 있는 데이터를 추출한다.

Metacritic_score = data1['Metacritic score']

df_Metacritic_score = pd.DataFrame(Metacritic_score)

df_Metacritic_score

filtered_Metacritic_score = df_Metacritic_score[(df_Metacritic_score != 0).all(axis=1)]

print("\nFiltered DataFrame:")
print(filtered_Metacritic_score)

mean_Metacritic_score = filtered_Metacritic_score.mean()
max_Metacritic_score = filtered_Metacritic_score.max()
min_Metacritic_score = filtered_Metacritic_score.min()
median_Metacritic_score = filtered_Metacritic_score.median()
std_Metacritic_score = filtered_Metacritic_score.std()

print("---------reslut---------")
print("Mean Values:")
print(mean_Metacritic_score)

print("Max Values:")
print(max_Metacritic_score)

print("Min Values:")
print(min_Metacritic_score)

print("Median Values:")
print(median_Metacritic_score)

print("Standard Deviation Values:")
print(std_Metacritic_score)

# 76983개의 게임 데이터 중 3792 개의 게임 데이터의 평균, 최대, 최소, 중간 값, 표준편차를 구했다.


Filtered DataFrame:
       Metacritic score
10                   62
15                   64
42                   53
44                   84
66                   89
...                 ...
75106                83
75197                77
76012                76
76071                83
76445                65

[3792 rows x 1 columns]
---------reslut---------
Mean Values:
Metacritic score    72.794831
dtype: float64
Max Values:
Metacritic score    97
dtype: int64
Min Values:
Metacritic score    20
dtype: int64
Median Values:
Metacritic score    74.0
dtype: float64
Standard Deviation Values:
Metacritic score    10.51976
dtype: float64


In [42]:
# Positive 칼럼 데이터가 어떤 것을 의미하는지 몰라 Metacritic score와 비슷하게 분석을 진행해보았다.

Positive = data1['Positive']

df_Positive = pd.DataFrame(Positive)

df_Positive

filtered_Positive = df_Positive[(df_Positive != 0).all(axis=1)]

print("\nFiltered DataFrame:")
print(filtered_Positive)

mean_Positive = filtered_Positive.mean()
max_Positive = filtered_Positive.max()
min_Positive = filtered_Positive.min()
median_Positive = filtered_Positive.median()
std_Positive = filtered_Positive.std()

print("---------reslut---------")
print("Mean Values:")
print(mean_Positive)

print("Max Values:")
print(max_Positive)

print("Min Values:")
print(min_Positive)

print("Median Values:")
print(median_Positive)

print("Standard Deviation Values:")
print(std_Positive)

# 76983개의 게임 데이터 중 57539개의 게임 데이터의 평균, 최대, 최소, 중간 값, 표준편차를 구했다.
# 평균 값이 1392인데 중앙 값이 19인 것을 미루어 보아 소수의 데이터가 굉장히 큰 값을 가지고 있는 왼쪽으로 꼬리가 긴 데이터를 가지고 있는 것을 알 수 있다.


Filtered DataFrame:
       Positive
0             6
1            53
3             3
4            50
5            87
...         ...
76974         2
76975         1
76979        66
76982        13
76985         2

[57539 rows x 1 columns]
---------reslut---------
Mean Values:
Positive    1392.261058
dtype: float64
Max Values:
Positive    5764420
dtype: int64
Min Values:
Positive    1
dtype: int64
Median Values:
Positive    19.0
dtype: float64
Standard Deviation Values:
Positive    29603.771748
dtype: float64


In [ ]:
# Score rank 칼럼 데이터는 42개의 데이터 만이 non-null 데이터 이므로
# 칼럼을 삭제하는 것이 좋을 것 같다.

In [62]:
# Recommendations 값이 0이라면 사실 상 해당 게임은 유저들이 전혀 하지 않는 게임이라고 할 수 있다.
# 따라서 이 데이터들을 우선적으로 삭제하려고 한다.

Recommendations = data1['Recommendations']

df_Recommendations = pd.DataFrame(Recommendations)

df_Recommendations

filtered_Recommendations = df_Recommendations[(df_Recommendations != 0).all(axis=1)]

print("\nFiltered DataFrame:")
print(filtered_Recommendations)

# 총 13057개의 데이터가 추천되었음을 알 수 있다.
# 이 데이터를 내림차순으로 정리하면 다음과 같다.

df_sorted = df_Recommendations.sort_values(by='Recommendations', ascending=False)

print("\nDataFrame Sorted by Recommendations in Descennding Order:")
print(df_sorted)

filtered_Recommendations = df_Recommendations[(df_Recommendations != 0).all(axis=1)]

mean_Recommendations = filtered_Recommendations.mean()
median_Recommendations= filtered_Recommendations.median()

print("Mean Values:")
print(mean_Recommendations)
print("Median Values:")
print(median_Recommendations)

# 평균 값이 4946인데 중앙 값이 410인 것을 미루어 보아 소수의 데이터가 굉장히 큰 값을 가지고 있는 왼쪽으로 꼬리가 긴 데이터를 가지고 있는 것을 알 수 있다.


Filtered DataFrame:
       Recommendations
10                 427
15                 285
17                1615
18                1144
22                1831
...                ...
76839              135
76859             1940
76879              262
76895              466
76971              190

[13057 rows x 1 columns]

DataFrame Sorted by Recommendations in Descennding Order:
       Recommendations
46158          3441592
8885           1616422
57205          1247051
38967           899838
21190           899613
...                ...
28475                0
28476                0
28477                0
28478                0
76986                0

[76987 rows x 1 columns]
Mean Values:
Recommendations    4946.849276
dtype: float64
Median Values:
Recommendations    410.0
dtype: float64


In [43]:
# Average playtime two weeks 값이 0이라면 사실 상 해당 게임은 유저들이 전혀 하지 않는 게임이라고 할 수 있다.
# 따라서 이 데이터들을 우선적으로 삭제하려고 한다.

Average_playtime_two_weeks = data1['Average playtime two weeks']

df_Average_playtime_two_weeks = pd.DataFrame(Average_playtime_two_weeks)

df_Average_playtime_two_weeks

filtered_Average_playtime_two_weeks = df_Average_playtime_two_weeks[(df_Average_playtime_two_weeks != 0).all(axis=1)]

print("\nFiltered DataFrame:")
print(filtered_Average_playtime_two_weeks)



Filtered DataFrame:
       Average playtime two weeks
47                            223
57                            230
66                             79
71                             20
93                             24
...                           ...
76321                          22
76336                         680
76624                          68
76859                         108
76879                         189

[1936 rows x 1 columns]


In [45]:
# Median playtime two weeks 값도 0이라면 사실 상 해당 게임은 유저들이 전혀 하지 않는 게임이라고 할 수 있다.
# 따라서 이 데이터들을 우선적으로 삭제하려고 한다.

Median_playtime_two_weeks = data1['Median playtime two weeks']

df_Median_playtime_two_weeks = pd.DataFrame(Median_playtime_two_weeks)

df_Median_playtime_two_weeks

filtered_Median_playtime_two_weeks = df_Median_playtime_two_weeks[(df_Median_playtime_two_weeks != 0).all(axis=1)]

print("\nFiltered DataFrame:")
print(filtered_Median_playtime_two_weeks)

#위의 두 데이터를 확인 해 보았을 때 실질적으로 유저들에게 플레이되는 게임 수는 1936개 이다.
#이 데이터 들을 중점적으로 전처리 하고 분석하면 좋을 것 같다. (나머지 데이터들은 추천하지 않는 것으로 판단(제 생각입니다))


Filtered DataFrame:
       Median playtime two weeks
47                           311
57                           130
66                            79
71                            20
93                            24
...                          ...
76321                         22
76336                        565
76624                         68
76859                        133
76879                        189

[1936 rows x 1 columns]


In [ ]:
# Publishers 칼럼 데이터는 사실 영화를 추천하는데 크게 중요하지 않을 것 같다.
# 칼럼을 삭제하는 것이 좋을 것 같다.

In [10]:
# Genres 데이터는 여러 object값을 가지므로 인코딩을 진행해보았다.

from sklearn.preprocessing import LabelEncoder

Genres = data1['Genres']

df_Genres = pd.DataFrame(Genres)

#label_encoder = LabelEncoder()
#df_Genres['Category_encoded_Genres'] = label_encoder.fit_transform(df_Genres['Genres'])

encoded_genres = df_Genres['Genres'].str.get_dummies(sep=',')

# 결과 출력
print("One-Hot Encoded Genres:")
print(encoded_genres)

print("Original DataFrame:")
print(df_Genres[['Genres']])
#print("\nDataFrame with Label Encoded Column:")
#print(one_hot_encoded_data)
print("One-Hot Encoded Genres:")
print(encoded_genres)

One-Hot Encoded Genres:
       360 Video  Accounting  Action  Adventure  Animation & Modeling  \
0              0           0       0          0                     0   
1              0           0       1          0                     0   
2              0           0       1          1                     0   
3              0           0       0          1                     0   
4              0           0       0          1                     0   
...          ...         ...     ...        ...                   ...   
76982          0           0       1          0                     0   
76983          0           0       1          1                     0   
76984          0           0       0          0                     0   
76985          0           0       0          0                     0   
76986          0           0       0          0                     0   

       Audio Production  Casual  Design & Illustration  Documentary  \
0                     0     

In [13]:
# Movies 칼럼 데이터는 링크로 나타내져 있고 링트를 들어가면 게임 진행 모습이 간단하게 나오는 영상이 나온다. 
# 칼럼을 삭제하는 것이 좋을 것 같다.